### ISSUE TITLE
Mutation and presentation are not deterministic

### ISSUE THREAD

**Issue by KoryNunn** [bitabase-old/bitabase-server#17]
righto.all does not guarantee order of execution, and as such the result of presentation and mutation can't be guaranteed.

https://github.com/bitabase/bitabase-server/blob/3d643aa10f1d1a4f4ea71a15d1f56dadc5c14f01/modules/applyMutationsToData.js#L18
https://github.com/bitabase/bitabase-server/blob/3d643aa10f1d1a4f4ea71a15d1f56dadc5c14f01/modules/applyPresentersToData.js#L12

These functions should:

1. Not mutate data, but return a new copy of the data for each step and pass it to the next
2. Use righto.reduce to pipe these steps together.

**Comment by markwylde** [comment]
Solved by https://github.com/bitabase/bitabase-server/pull/25/files#diff-c38072bef71f4fc9f14d41f12c27953cR20
